## Documentation for configuring a MySQL Cluster can be found at https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html#configuration
## The (yaml) configuration files can be found in the deploy folder

nameOverride: ""
fullnameOverride: ""

# If a GKE private cluster define the internal API IP. Obtain it by logging in to your GCP project using gcloud and then typing:
# gcloud container clusters get-credentials --internal-ip <gke-cluster-name> | grep privateEndpoint | awk '{print $NF}'
# If not a GKE private cluster, comment out this entry so that the server IP from kubeconfig is used
# kubernetesInternalApiServer:

# Image used for the job that will apply the operator yaml files for the relevant command (see below)
image:
  repository: gcr.io/saaspoc-gtso-enterprise-gke/gkegtsoent/mysql-operator
  tag: 1.0.7
  pullPolicy: IfNotPresent

podName: percona-xtradb-cluster-operator
